version: "3.1"
services:
  mongo:
    image: mongo
  redis:
    image: redis
  u-wave:
    build: .
    command: yarn start
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo
      - redis
    env_file:
      - .env
